### PR TITLE
Add support for reading bcrypt encrypted password

### LINKED ISSUE #4: htpasswd bcrypt support
Refers to https://github.com/verdaccio/verdaccio/issues/191

### PR DESCRIPTION
**Pull request by terribleplan**
**Type: feature**

The following has been addressed in the PR:

*  Resolves #4 (Adds support for reading bcrypt `$2(a|b|y)$` hashes)
*  Unit tests are included in the PR

**Description:**

Bcrypt "is currently considered to be very secure" according to the apache documentation on the `htpasswd` utility. The security comes through the design of the algorithm being such that brute-forcing is considerably harder than with many other algorithms including MD5 and SHA1. This is a huge benefit for security-oriented users. It will also help preventing users from being surprised when hash algorithm options in the `htpasswd` utility aren't supported.

### CODE REVIEW

**Comment by terribleplan** [comment]
```
Error: src/utils.js:6
  6: import bcrypt from 'bcryptjs';
                        ^^^^^^^^^^ bcryptjs. Required module not found
```

I don't understand why this failed. As you can see `bcryptjs` was added to `package.json` in my change.

**Comment by juanpicado** [comment]
It's a flow error. It's easy to fix.

Install

```
npm install -g flow-typed
```
and then

```
flow-typed create-stub bcryptjs
```
That will create a file on `flow-typed/npm`. Commit that file and will solve the issue.

**Comment by terribleplan** [comment]
Huh, that's a weird way for flow to present that error, but your instructions worked flawlessly to fix it.

Let me know if anything else needs to happen for this to land.

**Comment by juanpicado** [comment]
@ayusharma feel free to merge :)

**Comment by juanpicado** [comment]
@terribleplan @ayusharma one more thing ... the commit message does not follow our standard. If you merge you will need for now to write CHANGELOG manually.  Or create one, because there isn't one yet.

**Comment by terribleplan** [comment]
Pulling https://github.com/verdaccio/verdaccio/blob/master/CONTRIBUTING.md into this repo might be a good idea, as I had to go find it to figure out what your standard for commit messages is.

I amended the commit to conform, but now it looks like circle-ci isn't able to pull the code. Maybe try re-running it, as the content of the commit hasn't changed.

**Comment by juanpicado** [comment]
Thanks @terribleplan , that was quick :) ...

**Comment by juanpicado** [comment]
@ayusharma something weird is happening in CircleCI

```
remote: Counting objects: 11, done.        
remote: Compressing objects: 100% (2/2), done.        
remote: Total 11 (delta 8), reused 11 (delta 8), pack-reused 0        
Unpacking objects: 100% (11/11), done.
From github.com:verdaccio/verdaccio-htpasswd
 * [new ref]         refs/pull/23/head -> origin/pull/23
fatal: Could not parse object '83ca96794600061cebf59cdec65883ca96b76307'.
```

**Comment by ayusharma** [comment]
Sorry for late reply. :( I am out of station and having very bad internet connectivety. I’ll take a look in a day.

**Comment by ayusharma** [comment]
@terribleplan Thank you so much for your contribution 👍 Great work 🎉.

**Comment by terribleplan** [comment]
@ayusharma Glad to help. When would you expect a release to get cut? I am eager to get this running on my instance.

**Comment by juanpicado** [comment]
@terribleplan I'll release a new beta soon, in the next few days.

**Pull request merged**
